### ISSUE TITLE
Doesnt work at SourceTree app.

### ISSUE THREAD

**Issue by MikeKholomeev** [axxie/MouseImp#7]
Hi.
MouseImp doesnt work at SourceTree app. Is it implementable at all or it is not?

Thanks.

**Comment by axxie** [comment]
That depends on UI framework used.
However, I think with proper setup it should at least be able to emulate scroll events.
This mode is not convenient, in my opinion.
You can try to modify mimpwnds.xml file and see if it helps.
Just make sure to relaunch MIProHst.exe after modifications.

**Comment by MikeKholomeev** [comment]
Hi, **axxie**.
Thanks for the help.
Though I managed to turn on a horizontal scroll in VS2010, I didn't manage to turn it on in **SourceTree** app at all.

This shows me a "Window Spy" app:
```
Sourcetree
ahk_class HwndWrapper[SourceTree.exe;;885ee7c9-b971-4d2d-9ef1-076911829f98]
ahk_exe SourceTree.exe
ahk_pid 121732
```

This what I wrote in  mimpwnds.xml file:
```
<!-- Source Tree -->
<item wndclass="HwndWrapper[SourceTree" horscroll="false" lockedscrolldirection="true" lockedwheeldelta="true" />
```
, tried both - _horscroll="false"_ and _horscroll="true"_. Same results.

Any suggestions?

**Comment by MikeKholomeev** [comment]
Wow!
Sorry for the inconvenience. After reloading SourceTree app all starts working )))

Thanks a lot again!
